### ISSUE TITLE
SQL Error or missing database (incomplete input) with 1.1.4, works with 1.1.3

### ISSUE THREAD

**Issue by IzaacJ** [NivixX/NDatabase#8]
Hello.
Version 1.1.4 seems to cause me some issues, where 1.1.3 was working perfectly.

No changes in my code between testing 1.1.3 and 1.1.4, only difference is NDatabase version.
Note: All tests are done on a completely fresh server, ie no pre-existing configurations or files present.

Stacktrace:
```
[20:42:57 ERROR]: Could not pass event PlayerJoinEvent to IzMoney v0.0.1-SNAPSHOT
com.nivixx.ndatabase.api.exception.DatabaseException: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (incomplete input)
	at com.nivixx.ndatabase.core.dao.sqlite.SqliteDao.upsert(SqliteDao.java:89) ~[NDatabase.jar:?]
	at com.nivixx.ndatabase.core.RepositoryImpl.upsert(RepositoryImpl.java:89) ~[NDatabase.jar:?]
	at online.izz0.mc.izmoney.integrations.VaultEconomy.getPlayer(VaultEconomy.java:37) ~[IzMoney-0.0.1-SNAPSHOT.jar:?]
	at online.izz0.mc.izmoney.integrations.VaultEconomy.getBalance(VaultEconomy.java:88) ~[IzMoney-0.0.1-SNAPSHOT.jar:?]
	at online.izz0.mc.izmoney.managers.IzEconomy.getBalance(IzEconomy.java:33) ~[IzMoney-0.0.1-SNAPSHOT.jar:?]
	at online.izz0.mc.izmoney.events.PlayerJoinedEvent.onPlayerJoin(PlayerJoinedEvent.java:24) ~[IzMoney-0.0.1-SNAPSHOT.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor18.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-448]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.3.jar:git-Paper-448]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.3.jar:git-Paper-448]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:319) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:585) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:233) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (incomplete input)
	at org.sqlite.core.DB.newSQLException(DB.java:1030) ~[sqlite-jdbc-3.36.0.3.jar:?]
	at org.sqlite.core.DB.newSQLException(DB.java:1042) ~[sqlite-jdbc-3.36.0.3.jar:?]
	at org.sqlite.core.DB.throwex(DB.java:1007) ~[sqlite-jdbc-3.36.0.3.jar:?]
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method) ~[sqlite-jdbc-3.36.0.3.jar:?]
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:137) ~[sqlite-jdbc-3.36.0.3.jar:?]
	at org.sqlite.core.DB.prepare(DB.java:257) ~[sqlite-jdbc-3.36.0.3.jar:?]
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45) ~[sqlite-jdbc-3.36.0.3.jar:?]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30) ~[sqlite-jdbc-3.36.0.3.jar:?]
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25) ~[sqlite-jdbc-3.36.0.3.jar:?]
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35) ~[sqlite-jdbc-3.36.0.3.jar:?]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241) ~[sqlite-jdbc-3.36.0.3.jar:?]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205) ~[sqlite-jdbc-3.36.0.3.jar:?]
	at com.nivixx.ndatabase.core.dao.sqlite.SqliteDao.upsert(SqliteDao.java:71) ~[NDatabase.jar:?]
	... 24 more
```

**Comment by NivixX** [comment]
Hello, thanks for the report.
I've been able to reproduce it and fix it, unit test were added to cover this case.

You can try the 1.1.5
[https://github.com/NivixX/NDatabase/releases/tag/1.1.5](https://github.com/NivixX/NDatabase/releases/tag/1.1.5)

**Comment by IzaacJ** [comment]
> Hello, thanks for the report. I've been able to reproduce it and fix it, unit test were added to cover this case.
> 
> You can try the 1.1.5 https://github.com/NivixX/NDatabase/releases/tag/1.1.5
> 
> Note: I assume you weren't using Indexed annotation in your data model

Awesome! It is working now :D And yeah, you assumed correct, I'm not using indexed annotations :)
